name: ci

on:
  push:
    branches: main
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '45 4 * * *'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: install rustup and rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2020-09-28
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.0"
      - name: setup cluster
        run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/DominicBurkart/turbolift/master/examples/kubernetes_example/setup_cluster.sh | sh -s
      - uses: actions/checkout@v2
        with:
          path: './turbolift_example'
      - name: run
        run: cd turbolift_example && RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo run +nightly --features distributed
  local:
    runs-on: ubuntu-latest
    steps:
      - name: install rustup and rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2020-09-28
      - uses: actions/checkout@v2
        with:
          path: './turbolift_example'
      - name: run
        run: cd turbolift_example && RUSTFLAGS='--cfg procmacro2_semver_exempt -Z macro-backtrace' cargo run +nightly